name: Reset Supabase Staging DB

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight UTC
  workflow_dispatch: # allow manual trigger

jobs:
  reset-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        run: |
          curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs
          npm install supabase --save-dev

      - name: Link to Supabase project
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
        run: |
          npx supabase link --project-ref $SUPABASE_PROJECT_ID

      - name: Reset DB (apply migrations + seed.sql if exists)
        run: |
          npx supabase db reset --linked

      - name: Run addHadiah.sql
        run: |
          npx supabase db query addHadiah.sql --linked
